version: "3.9"

services:
  server:
    build: ./app
    env_file:
      - .env
    environment:
      - PORT=8080
      - POSTGRES_PORT=5432
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./app:/app"

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d secure_purchase_order" ]

volumes:
  db-data:



